# Generated by Django 3.1.2 on 2020-10-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('to', models.CharField(default='', max_length=50, null=True, verbose_name='to')),
                ('order', models.IntegerField(verbose_name='order')),
            ],
            options={
                'verbose_name': 'Menu_Item',
                'verbose_name_plural': 'Menu_Items',
            },
        ),
    ]
