# Generated by Django 3.1.2 on 2020-11-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201103_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerinfo',
            name='footer_to',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='to'),
        ),
    ]
