# Generated by Django 3.1.2 on 2020-11-03 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_footerinfo_footer_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerinfo',
            name='footer_to',
        ),
    ]
