# Generated by Django 3.1.2 on 2020-11-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_footerinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterInfo',
        ),
    ]
