# Generated by Django 3.1.2 on 2020-11-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201104_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetitle',
            name='slogan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
