# Generated by Django 3.1.2 on 2020-11-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_pagetitle_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_info',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_message',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pagetitle',
            name='slogan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
