# Generated by Django 3.1.2 on 2020-11-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20201105_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetitle',
            name='course_message',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagetitle',
            name='course_text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagetitle',
            name='featured_text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagetitle',
            name='featured_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
