# Generated by Django 3.1.2 on 2020-11-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20201105_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetitle',
            name='join_text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagetitle',
            name='join_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagetitle',
            name='sign_up_text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagetitle',
            name='sign_up_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
