# Generated by Django 3.1.2 on 2020-11-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_pagetitle_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetitle',
            name='sign_up_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
