# Generated by Django 3.1.2 on 2020-11-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_pagetitle_sign_up_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerinfo',
            name='footer_info',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
