# Generated by Django 3.1.2 on 2020-11-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_footerinfo_footer_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerinfo',
            name='footer_info1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='footer_info2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
