# Generated by Django 3.1.2 on 2020-11-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20201106_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc_category', models.CharField(max_length=50, null=True)),
                ('fc_price', models.FloatField(null=True)),
                ('fc_image', models.ImageField(null=True, upload_to='')),
                ('fc_message', models.CharField(max_length=150, null=True)),
                ('fc_title', models.CharField(max_length=50, null=True)),
                ('fc_info', models.CharField(max_length=50, null=True)),
                ('fc_author_image', models.ImageField(null=True, upload_to='')),
                ('fc_author_name', models.CharField(max_length=50, null=True)),
                ('fc_author_position', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Featured_Course',
                'verbose_name_plural': 'Featured_Courses',
            },
        ),
    ]
