# Generated by Django 3.1.2 on 2020-11-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20201106_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredcourses',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='featuredcourses',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
