# Generated by Django 3.1.2 on 2020-11-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20201106_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('body_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('about_us_title', models.CharField(max_length=50, null=True)),
                ('about_us_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
