# Generated by Django 3.1.2 on 2020-11-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_courses_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('page_courses_body_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('page_courses_price', models.CharField(max_length=50, null=True)),
                ('pc_author_image', models.ImageField(null=True, upload_to='')),
                ('pc_author_name', models.CharField(max_length=50, null=True)),
                ('pc_author_position', models.CharField(max_length=50, null=True)),
                ('pc_message', models.CharField(max_length=250, null=True)),
                ('pc_title', models.CharField(max_length=50, null=True)),
                ('pc_btn', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='aboutus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
