# Generated by Django 3.1.2 on 2020-11-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20201106_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecourses',
            name='pc_info',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
