# Generated by Django 3.1.2 on 2020-11-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_pagecourses_pc_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn_main_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('pn_body_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('pn_body_title', models.CharField(max_length=50, null=True)),
                ('pn_author_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('pn_author_name', models.CharField(max_length=50, null=True)),
                ('pn_author_position', models.CharField(max_length=50, null=True)),
                ('pn_author_date', models.CharField(max_length=50, null=True)),
                ('pn_author_comment', models.CharField(max_length=50, null=True)),
                ('pn_body_text', models.TextField(blank=True, null=True)),
                ('pn_body_btn', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
