# Generated by Django 3.1.2 on 2020-11-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_newsidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsidebar',
            name='ns_archives_info',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newsidebar',
            name='ns_categories_info',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newsidebar',
            name='ns_month_info',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
