# Generated by Django 3.1.2 on 2020-11-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_pagecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerinfo',
            name='footer_category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
