# Generated by Django 3.1.2 on 2020-11-12 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_category_category_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerinfo',
            name='footer_title',
        ),
        migrations.AddField(
            model_name='course',
            name='course_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
            preserve_default=False,
        ),
    ]
