# Generated by Django 3.1.2 on 2020-11-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20201112_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
