# Generated by Django 3.1.2 on 2020-11-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20201113_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
