# Generated by Django 3.1.2 on 2020-11-13 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_course_course_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_url',
        ),
    ]
