# Generated by Django 3.1.2 on 2020-11-13 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_course_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.menu'),
        ),
    ]
