# Generated by Django 3.1.2 on 2020-11-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20201115_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredcourses',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
