# Generated by Django 3.1.2 on 2020-11-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_featuredcourses_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredcourses',
            old_name='slug',
            new_name='fc_slug',
        ),
    ]
