# Generated by Django 3.1.2 on 2020-11-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20201116_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredcourses',
            old_name='fc_slug',
            new_name='slug',
        ),
    ]
