# Generated by Django 3.1.2 on 2020-11-16 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_auto_20201116_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsidebar',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pagenew'),
        ),
        migrations.AddField(
            model_name='pagenew',
            name='pn_body_fulltext',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagenew',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
