# Generated by Django 3.1.2 on 2020-11-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20201118_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
