# Generated by Django 3.1.2 on 2020-11-18 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_auto_20201119_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.featuredcourses'),
        ),
    ]
