# Generated by Django 3.1.2 on 2020-11-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20201119_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='Inha@mail', max_length=254),
        ),
    ]
